const ImagePath = {
  addicon: require('../assests/images/iconadd.png'),
  backicon: require('../assests/images/back_icon.png'),
  spotifyicon: require('../assests/images/SpotifyIcon.png'),
  albumsPic: require('../assests/images/Albums.png'),
  Splash : require('../assests/images/splash_back.png'),
  applogo: require('../assests/images/new_logo.png'),
  copyright: require('../assests/images/Copyright.png'),
  applemusic: require('../assests/images/itunesicon.png'),
  homeactive: require('../assests/images/active_home_white.png'),
  homeinactive: require('../assests/images/icon-home.png'),
  sendiconcopy:require('../assests/images/icon-send-copy.png'),
  sendicon:require('../assests/images/icon-send-new.png'),
  iconbox:require('../assests/images/icon-box.png'),
  greyplus:require('../assests/images/greyplus.png'),
  greycross:require('../assests/images/greycross.png'),
  searchactive: require('./images/active_seach_white.png'),
  searchinactive: require('./images/inactive_seach.png'),
  addbtn: require('./images/Button-Add.png'),
  notificationactive: require('./images/active_bell_white.png'),
  notificationinactive: require('./images/inactive_bell.png'),
  backwardicon:require('./images/backwardicon.png'),
  forwardicon:require('./images/forwardicon.png'),
  boxicon:require('./images/icon-box-new.png'),
  boxactive: require('./images/active_saved_song_white.png'),
  boxinactive: require('./images/in_active_saved_song.png'),
  dp: require('../assests/images/dp.png'),
  dp1: require('../assests/images/Mask.png'),
  dp2: require('../assests/images/Group1.png'),
  iconmenu: require('../assests/images/icon-menu.png'),
  playicon: require('../assests/images/playicon.png'),
  reactionicon: require('../assests/images/reactionicon.png'),
  commenticon:require('../assests/images/Icon-comment.png'),
  pauseicon:require('../assests/images/pauseicon.png'),
  settings: require('./images/settings.png'),
  blankreactionbg:require('./images/Artwork.png'),
  profiletrack1: require('./images/profiletrack1.png'),
  profiletrack2: require('./images/profiletrack2.png'),
  profiletrack3: require('./images/profiletrack3.png'),
  profiletrack4: require('./images/profiletrack4.png'),
  profiletrack5: require('./images/profiletrack5.png'),
  profiletrack6: require('./images/profiletrack.png'),
  gradientbar: require('./images/rectanglegradien.png'),
  change: require('./images/change.png'),
  play: require('./images/play.png'),
  iconadd:require('./images/iconadd.png'),
  searchicon: require('./images/icons-search-black.png'),
  threedots: require('./images/moredots.png'),
  unsaved: require('./images/whiteunsave.png'),
  inbox: require('./images/inbox.png'),
  noposts: require('./images/NoPosts.png'),
  facebook: require('./images/facebook.png'),
  newmessage: require('./images/Iconnewmessage.png'),
  green_tick: require('./images/green_tick.png'),
  page_gradient: require('./images/page_gradient.png'),
  more_copy: require('./images/more_copy.png'),
  more_unfollow: require('./images/more_unfollow.png'),
  home_icon_choona: require('./images/home_icon_choona.png'),
  gradient_border_horizontal: require('./images/gradient_border_horizontal.png'),
  music_icon: require('./images/music_icon.png'),
  headerShadow: require('./images/headerShadow.png'),
  add_white: require('./images/add_white.png'),
  searchicongrey: require('./images/searchIcongrey.png'),
  user: require('./images/user.png'),
  crossIcon: require('./images/crossIcon.png'),
  genretrack: require('./images/img1.png'),
  genretrack2: require('./images/img2.png'),
  genretrack3: require('./images/img3.png'),
  donw_arrow_solid: require('./images/donw_arrow_solid.png'),
  comment_grey: require('./images/comment_grey.png'),
  musicplayerbarbg: require('./images/bgmusicbar.png'),
  apple_icon_round: require('./images/apple_icon_round.png'),
  pause: require('./images/pause.png'),
  appIcon512: require('./images/appIcon512.png'),
};

export default ImagePath;

