
export const ASYNC_STORAGE_REQUEST = "ASYNC_STORAGE_REQUEST";
export const ASYNC_STORAGE_SUCCESS = "ASYNC_STORAGE_SUCCESS";
export const ASYNC_STORAGE_FAILURE = "ASYNC_STORAGE_FAILURE";
export const ASYNC_STORAGE_CLEAR = "ASYNC_STORAGE_CLEAR";

export const GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";

export const USER_SEARCH_REQUEST = "USER_SEARCH_REQUEST";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";
export const USER_SEARCH_FAILURE = "USER_SEARCH_FAILURE";

export const USER_FOLLOW_UNFOLLOW_REQUEST = "USER_FOLLOW_UNFOLLOW_REQUEST";
export const USER_FOLLOW_UNFOLLOW_SUCCESS = "USER_FOLLOW_UNFOLLOW_SUCCESS";
export const USER_FOLLOW_UNFOLLOW_FAILURE = "USER_FOLLOW_UNFOLLOW_FAILURE";

export const OTHERS_PROFILE_REQUEST = "OTHERS_PROFILE_REQUEST";
export const OTHERS_PROFILE_SUCCESS = "OTHERS_PROFILE_SUCCESS";
export const OTHERS_PROFILE_FAILURE = "OTHERS_PROFILE_FAILURE";

export const SEARCH_SONG_REQUEST_FOR_POST_REQUEST = "SEARCH_SONG_REQUEST_FOR_POST_REQUEST";
export const SEARCH_SONG_REQUEST_FOR_POST_SUCCESS = "SEARCH_SONG_REQUEST_FOR_POST_SUCCESS";
export const SEARCH_SONG_REQUEST_FOR_POST_FAILURE = "SEARCH_SONG_REQUEST_FOR_POST_FAILURE";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const HOME_PAGE_REQUEST = "HOME_PAGE_REQUEST";
export const HOME_PAGE_SUCCESS = "HOME_PAGE_SUCCESS";
export const HOME_PAGE_FAILURE = "HOME_PAGE_FAILURE";

export const SAVE_SONGS_REQUEST = "SAVE_SONGS_REQUEST";
export const SAVE_SONGS_SUCCESS = "SAVE_SONGS_SUCCESS";
export const SAVE_SONGS_FAILURE = "SAVE_SONGS_FAILURE";

export const SAVED_SONGS_LIST_REQUEST = "SAVED_SONGS_LIST_REQUEST";
export const SAVED_SONGS_LIST_SUCCESS = "SAVED_SONGS_LIST_SUCCESS";
export const SAVED_SONGS_LIST_FAILURE = "SAVED_SONGS_LIST_FAILURE";

export const UNSAVE_SONG_REQUEST = "UNSAVE_SONG_REQUEST";
export const UNSAVE_SONG_SUCCESS = "UNSAVE_SONG_SUCCESS";
export const UNSAVE_SONG_FAILURE = "UNSAVE_SONG_FAILURE";

export const COMMENT_ON_POST_REQUEST = "COMMENT_ON_POST_REQUEST";
export const COMMENT_ON_POST_SUCCESS = "COMMENT_ON_POST_SUCCESS";
export const COMMENT_ON_POST_FAILURE = "COMMENT_ON_POST_FAILURE";

export const FOLLOWER_LIST_REQUEST = "FOLLOWER_LIST_REQUEST";
export const FOLLOWER_LIST_SUCCESS = "FOLLOWER_LIST_SUCCESS";
export const FOLLOWER_LIST_FAILURE = "FOLLOWER_LIST_FAILURE";

export const FOLLOWING_LIST_REQUEST = "FOLLOWING_LIST_REQUEST";
export const FOLLOWING_LIST_SUCCESS = "FOLLOWING_LIST_SUCCESS";
export const FOLLOWING_LIST_FAILURE = "FOLLOWING_LIST_FAILURE";

export const REACTION_ON_POST_REQUEST = "REACTION_ON_POST_REQUEST";
export const REACTION_ON_POST_SUCCESS = "REACTION_ON_POST_SUCCESS";
export const REACTION_ON_POST_FAILURE = "REACTION_ON_POST_FAILURE";

export const ACTIVITY_LIST_REQUEST = "ACTIVITY_LIST_REQUEST";
export const ACTIVITY_LIST_SUCCESS = "ACTIVITY_LIST_SUCCESS";
export const ACTIVITY_LIST_FAILURE = "ACTIVITY_LIST_FAILURE";

export const CREATE_CHAT_TOKEN_REQUEST = "CREATE_CHAT_TOKEN_REQUEST";
export const CREATE_CHAT_TOKEN_SUCCESS = "CREATE_CHAT_TOKEN_SUCCESS";
export const CREATE_CHAT_TOKEN_FAILURE = "CREATE_CHAT_TOKEN_FAILURE";

export const SEND_CHAT_MESSAGE_REQUEST = "SEND_CHAT_MESSAGE_REQUEST";
export const SEND_CHAT_MESSAGE_SUCCESS = "SEND_CHAT_MESSAGE_SUCCESS";
export const SEND_CHAT_MESSAGE_FAILURE = "SEND_CHAT_MESSAGE_FAILURE";

export const SAVE_SONG_REFERENCE_REQUEST = "SAVE_SONG_REFERENCE_REQUEST";
export const SAVE_SONG_REFERENCE_SUCCESS = "SAVE_SONG_REFERENCE_SUCCESS";
export const SAVE_SONG_REFERENCE_FAILURE = "SAVE_SONG_REFERENCE_FAILURE";

export const GET_CHAT_LIST_REQUEST = "GET_CHAT_LIST_REQUEST";
export const GET_CHAT_LIST_SUCCESS = "GET_CHAT_LIST_SUCCESS";
export const GET_CHAT_LIST_FAILURE = "GET_CHAT_LIST_FAILURE";

export const CHAT_LOAD_REQUEST = "CHAT_LOAD_REQUEST";
export const CHAT_LOAD_SUCCESS = "CHAT_LOAD_SUCCESS";
export const CHAT_LOAD_FAILURE = "CHAT_LOAD_FAILURE";

export const FEATURED_SONG_SEARCH_REQUEST = "FEATURED_SONG_SEARCH_REQUEST";
export const FEATURED_SONG_SEARCH_SUCCESS = "FEATURED_SONG_SEARCH_SUCCESS";
export const FEATURED_SONG_SEARCH_FAILURE = "FEATURED_SONG_SEARCH_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const SEARCH_POST_REQUEST = "SEARCH_POST_REQUEST";
export const SEARCH_POST_SUCCESS = "SEARCH_POST_SUCCESS";
export const SEARCH_POST_FAILURE = "SEARCH_POST_FAILURE";

export const TOP_50_SONGS_REQUEST = "TOP_50_SONGS_REQUEST";
export const TOP_50_SONGS_SUCCESS = "TOP_50_SONGS_SUCCESS";
export const TOP_50_SONGS_FAILURE = "TOP_50_SONGS_FAILURE";

export const GET_POST_FROM_TOP_50_REQUEST = "GET_POST_FROM_TOP_50_REQUEST";
export const GET_POST_FROM_TOP_50_SUCCESS = "GET_POST_FROM_TOP_50_SUCCESS";
export const GET_POST_FROM_TOP_50_FAILURE = "GET_POST_FROM_TOP_50_FAILURE";

export const GET_USER_FROM_HOME_REQUEST = "GET_USER_FROM_HOME_REQUEST";
export const GET_USER_FROM_HOME_SUCCESS = "GET_USER_FROM_HOME_SUCCESS";
export const GET_USER_FROM_HOME_FAILURE = "GET_USER_FROM_HOME_FAILURE";

export const GET_CURRENT_PLAYER_POSITION_REQUEST = "GET_CURRENT_PLAYER_POSITION_REQUEST";
export const GET_CURRENT_PLAYER_POSITION_SUCCESS = "GET_CURRENT_PLAYER_POSITION_SUCCESS";
export const GET_CURRENT_PLAYER_POSITION_FAILURE = "GET_CURRENT_PLAYER_POSITION_FAILURE";

export const RESUME_PLAYER_REQUEST = "RESUME_PLAYER_REQUEST";
export const RESUME_PLAYER_SUCCESS = "RESUME_PLAYER_SUCCESS";
export const RESUME_PLAYER_FAILURE = "RESUME_PLAYER_FAILURE";

export const PAUSE_PLAYER_REQUEST = "PAUSE_PLAYER_REQUEST";
export const PAUSE_PLAYER_SUCCESS = "PAUSE_PLAYER_SUCCESS";
export const PAUSE_PLAYER_FAILURE = "PAUSE_PLAYER_FAILURE";

export const PLAYER_SEEK_TO_REQUEST = "PLAYER_SEEK_TO_REQUEST";
export const PLAYER_SEEK_TO_SUCCESS = "PLAYER_SEEK_TO_SUCCESS";
export const PLAYER_SEEK_TO_FAILURE = "PLAYER_SEEK_TO_FAILURE";

export const SEARCH_MESSAGE_REQUEST = "SEARCH_MESSAGE_REQUEST";
export const SEARCH_MESSAGE_SUCCESS = "SEARCH_MESSAGE_SUCCESS";
export const SEARCH_MESSAGE_FAILURE = "SEARCH_MESSAGE_FAILURE";

export const COUNTRY_CODE_REQUEST = "COUNTRY_CODE_REQUEST";
export const COUNTRY_CODE_SUCCESS = "COUNTRY_CODE_SUCCESS";
export const COUNTRY_CODE_FAILURE = "COUNTRY_CODE_FAILURE";

export const TOP_5_FOLLOWED_USER_REQUEST = "TOP_5_FOLLOWED_USER_REQUEST";
export const TOP_5_FOLLOWED_USER_SUCCESS = "TOP_5_FOLLOWED_USER_SUCCESS";
export const TOP_5_FOLLOWED_USER_FAILURE = "TOP_5_FOLLOWED_USER_FAILURE";

export const GET_USERS_FROM_CONTACTS_REQUEST = "GET_USERS_FROM_CONTACTS_REQUEST";
export const GET_USERS_FROM_CONTACTS_SUCCESS = "GET_USERS_FROM_CONTACTS_SUCCESS";
export const GET_USERS_FROM_CONTACTS_FAILURE = "GET_USERS_FROM_CONTACTS_FAILURE";

export const GET_SONG_FROM_ISRC_REQUEST = "GET_SONG_FROM_ISRC_REQUEST";
export const GET_SONG_FROM_ISRC_SUCCESS = "GET_SONG_FROM_ISRC_SUCCESS";
export const GET_SONG_FROM_ISRC_FAILURE = "GET_SONG_FROM_ISRC_FAILURE";

export const UPDATE_MESSEAGE_COMMENTS_REQUEST = "UPDATE_MESSEAGE_COMMENTS_REQUEST";
export const UPDATE_MESSEAGE_COMMENTS_SUCCESS = "UPDATE_MESSEAGE_COMMENTS_SUCCESS";
export const UPDATE_MESSEAGE_COMMENTS_FAILURE = "UPDATE_MESSEAGE_COMMENTS_FAILURE";

export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAILURE = "DELETE_MESSAGE_FAILURE";

export const GET_USER_PLAYLIST_REQUEST = "GET_USER_PLAYLIST_REQUEST";
export const GET_USER_PLAYLIST_SUCCESS = "GET_USER_PLAYLIST_SUCCESS";
export const GET_USER_PLAYLIST_FAILURE = "GET_USER_PLAYLIST_FAILURE";

export const ADD_SONG_TO_PLAYLIST_REQUEST = "ADD_SONG_TO_PLAYLIST_REQUEST";
export const ADD_SONG_TO_PLAYLIST_SUCCESS = "ADD_SONG_TO_PLAYLIST_SUCCESS";
export const ADD_SONG_TO_PLAYLIST_FAILURE = "ADD_SONG_TO_PLAYLIST_FAILURE";

export const CREATE_CHAT_TOKEN_FROM_SEARCH_REQUEST = "CREATE_CHAT_TOKEN_FROM_SEARCH_REQUEST";
export const CREATE_CHAT_TOKEN_FROM_SEARCH_SUCCESS = "CREATE_CHAT_TOKEN_FROM_SEARCH_SUCCESS";
export const CREATE_CHAT_TOKEN_FROM_SEARCH_FAILURE = "CREATE_CHAT_TOKEN_FROM_SEARCH_FAILURE";

export const CREATE_CHAT_TOKEN_FROM_SAVEDSONG_REQUEST = "CREATE_CHAT_TOKEN_FROM_SAVEDSONG_REQUEST";
export const CREATE_CHAT_TOKEN_FROM_SAVEDSONG_SUCCESS = "CREATE_CHAT_TOKEN_FROM_SAVEDSONG_SUCCESS";
export const CREATE_CHAT_TOKEN_FROM_SAVEDSONG_FAILURE = "CREATE_CHAT_TOKEN_FROM_SAVEDSONG_FAILURE";

export const DUMMY_ACTION_REQUEST = "DUMMY_ACTION_REQUEST";
export const DUMMY_ACTION_SUCCESS = "DUMMY_ACTION_SUCCESS";

export const FOLLOWING_SEARCH_REQUEST = "FOLLOWING_SEARCH_REQUEST";
export const FOLLOWING_SEARCH_SUCCESS = "FOLLOWING_SEARCH_SUCCESS";

export const FOLLOWER_SEARCH_REQUEST = "FOLLOWER_SEARCH_REQUEST";
export const FOLLOWER_SEARCH_SUCCESS = "FOLLOWER_SEARCH_SUCCESS";

export const DELETE_CONVERSATION_REQUEST = "DELETE_CONVERSATION_REQUEST";
export const DELETE_CONVERSATION_SUCCESS = "DELETE_CONVERSATION_SUCCESS";
export const DELETE_CONVERSATION_FAILURE = "DELETE_CONVERSATION_FAILURE";
